# Generated by Django 4.2 on 2024-01-12 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about", options={"verbose_name": "关于", "verbose_name_plural": "关于"},
        ),
        migrations.RemoveField(model_name="about", name="sort_by",),
    ]
