# Generated by Django 4.2 on 2024-01-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_about_options_remove_about_sort_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="short_title",
            field=models.CharField(max_length=20, null=True, verbose_name="文章短标题"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=40, verbose_name="标题"),
        ),
    ]
