# Generated by Django 4.2 on 2024-01-27 23:37

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_short_title_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="cover/default.png",
                help_text="5:4上传比例",
                upload_to="cover",
                verbose_name="封面",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="cover",
            field=imagekit.models.fields.ProcessedImageField(
                default="cover/default.png",
                help_text="5：3上传比例",
                upload_to="cover",
                verbose_name="专题封面",
            ),
        ),
    ]
