# Generated by Django 4.2 on 2024-01-28 15:43

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_cover_alter_subject_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="vip",
            field=models.BooleanField(default=False, verbose_name="vip"),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="cover/default.png",
                help_text="5:3上传比例",
                upload_to="cover",
                verbose_name="封面",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="cover",
            field=imagekit.models.fields.ProcessedImageField(
                default="cover/default.png",
                help_text="5:3上传比例",
                upload_to="cover",
                verbose_name="专题封面",
            ),
        ),
    ]
