# Generated by Django 4.2 on 2024-02-03 22:06

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_article_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="about", name="title",),
        migrations.AlterField(
            model_name="about",
            name="content",
            field=mdeditor.fields.MDTextField(verbose_name="描述内容"),
        ),
    ]
