# Generated by Django 4.2 on 2024-02-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_about_title_alter_about_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="名称")),
                ("url", models.CharField(max_length=250, verbose_name="链接地址")),
                ("description", models.CharField(max_length=250, verbose_name="描述")),
                ("sort_by", models.IntegerField(default=999, verbose_name="排序")),
            ],
            options={"verbose_name": "工具", "verbose_name_plural": "工具",},
        ),
        migrations.CreateModel(
            name="ToolSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="名称")),
                ("sort_by", models.IntegerField(default=999, verbose_name="排序")),
            ],
            options={"verbose_name": "工具集合", "verbose_name_plural": "工具集合",},
        ),
    ]
