# Generated by Django 4.2 on 2024-02-03 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_tool_toolset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="toolset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.toolset",
                verbose_name="合集",
            ),
        ),
    ]
