# Generated by Django 4.2 on 2024-01-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0002_ouser_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="ouser",
            name="vip",
            field=models.BooleanField(default=False, verbose_name="用户是否是vip"),
        ),
    ]
